// Defaults
#define MODBUSTOOLS_DEFAULT_UART "/dev/ttyUSB0"
#define MODBUSTOOLS_DEFAULT_BAUDRATE 115200
#define MODBUSTOOLS_DEFAULT_DATABITS 8
#define MODBUSTOOLS_DEFAULT_PARITY 'N'
#define MODBUSTOOLS_DEFAULT_STOPBITS 2
#define MODBUSTOOLS_DEFAULT_RETRIES 4
#define MODBUSTOOLS_DEFAULT_OUTFORMAT 'D'

// Internal defaults
#define MODBUSTOOLS_DEFAULT_READ_RTYPE 'i'
#define MODBUSTOOLS_DEFAULT_WRITE_RTYPE 'r'


// Some types
typedef union {
    float    fl;
    uint32_t dw;
    uint16_t w[2];
} Float32;
