// Defaults
#define MODBUSTOOLS_DEFAULT_UART "/dev/ttyUSB0"
#define MODBUSTOOLS_DEFAULT_BAUDRATE 19200
#define MODBUSTOOLS_DEFAULT_DATABITS 8
#define MODBUSTOOLS_DEFAULT_PARITY 'E'
#define MODBUSTOOLS_DEFAULT_STOPBITS 1
#define MODBUSTOOLS_DEFAULT_RETRIES 4
#define MODBUSTOOLS_DEFAULT_OUTFORMAT 'H'

// Internal defaults
#define MODBUSTOOLS_DEFAULT_READ_RTYPE 'i'
#define MODBUSTOOLS_DEFAULT_WRITE_RTYPE 'r'
